name: Lint and Publish
on: push
jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "todo"
          - name: Install dependencies
            run: npm install
          - name: Run lint
            run: npm run lint